# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z7n6Q8ebBMxhov9Aw5k2bYlNN85-6dHJ
"""

# ============================================================
#  MAIN.PY — Pilote Global du Pipeline de Data Science
#  Exécution séquentielle des TPs 1 à 8
# ============================================================

import os
import warnings

# Importation des modules de chaque TP
import tp1_collecte_des_donnees as tp1
import tp2_clustering as tp2
import tp3_classification as tp3
import tp4_regression as tp4
import tp5_deep_learning as tp5
import tp6_scrapping as tp6
import tp7_finetuning_bert as tp7
import tp8_classification as tp8

warnings.filterwarnings("ignore")

# Configuration globale
COMPANIES = tp1.companies
API_KEY = os.environ.get("NEWS_API_KEY", "VOTRE_CLE_API_ICI")

def main():
    print("🚀 Démarrage du Pipeline Global (TP1 à TP8)...")

    # 1. Collecte des données
    print("\n" + "="*60 + "\n 1. TP1 : Collecte des données\n" + "="*60)
    tp1.scrape_financial_ratios()
    tp1.scrape_historical_prices()

    # 2. Clustering
    print("\n" + "="*60 + "\n 2. TP2 : Clustering\n" + "="*60)
    tp2.run_tp2()

    # 3. Classification
    print("\n" + "="*60 + "\n 3. TP3 : Classification (Buy/Hold/Sell)\n" + "="*60)
    tp3.run_tp3()

    # 4. Régression
    print("\n" + "="*60 + "\n 4. TP4 : Régression (ML classique)\n" + "="*60)
    tp4.run_tp4()

    # 5. Deep Learning
    print("\n" + "="*60 + "\n 5. TP5 : Deep Learning (RNN/LSTM)\n" + "="*60)
    tp5.run_tp5()

    # 6. Scraping News
    print("\n" + "="*60 + "\n 6. TP6 : Scraping des News\n" + "="*60)
    tp6.run_tp6(COMPANIES, API_KEY)

    # 7. Finetuning prend bcp de temps
    TRAIN_MODELS_NLP = False  # Mettre à True uniquement si vous voulez re-finetuner le modèle

    if TRAIN_MODELS_NLP:
        print("\n--- [TP7] Finetuning des modèles NLP ---")
        tp7.run_tp7() # Cette fonction prendra beaucoup de temps !

    # 8. Analyse de Sentiment (TP8)
    print("\n" + "="*60 + "\n 7. TP8 : Analyse de Sentiment vs Prix\n" + "="*60)
    tp8.run_tp8(COMPANIES)

    print("\n" + "="*60)
    print("✅ Pipeline complet terminé avec succès !")
    print("Tous les résultats (CSV, JSON, Graphiques) sont disponibles dans les dossiers.")
    print("="*60)

main()
