# -*- coding: utf-8 -*-
"""Tp1_collecte_des_données.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18Rz0UHKN0m_D4GECM03J4weEYN17X-Yr
"""

# ============================================================
#  PRATIQUE DE LA DATA SCIENCE — TP 1
#  Collecte de données financières avec yfinance
#
#  Structure : fonctions autonomes appelables depuis main.py
#  Les dates sont calculées dynamiquement à chaque exécution.
# ============================================================

import yfinance as yf
import pandas as pd
import os
import time
from datetime import datetime, timedelta

# ─────────────────────────────────────────────────────────────
# CONSTANTES PARTAGÉES
# ─────────────────────────────────────────────────────────────

# Pour récuperer la date d'hier
def get_date_range(years: int = 5):
    """
    ---------------
    Les APIs financières (Yahoo Finance) ne fournissent le cours de clôture
    d'une journée qu'après la fermeture du marché. Si on exécute le pipeline
    en cours de journée, aujourd'hui n'est pas encore disponible.
    On prend donc J-1 comme dernière date disponible.
    """
    end_date   = datetime.today() - timedelta(days=1)
    start_date = end_date - timedelta(days=years * 365)

    return start_date.strftime("%Y-%m-%d"), end_date.strftime("%Y-%m-%d")


companies = {
    "Apple": "AAPL",
    "Microsoft": "MSFT",
    "Amazon": "AMZN",
    "Alphabet": "GOOGL",
    "Meta": "META",
    "Tesla": "TSLA",
    "NVIDIA": "NVDA",
    "Samsung": "005930.KS",
    "Tencent": "TCEHY",
    "Alibaba": "BABA",
    "IBM": "IBM",
    "Intel": "INTC",
    "Oracle": "ORCL",
    "Sony": "SONY",
    "Adobe": "ADBE",
    "Netflix": "NFLX",
    "AMD": "AMD",
    "Qualcomm": "QCOM",
    "Cisco": "CSCO",
    "JP Morgan": "JPM",
    "Goldman Sachs": "GS",
    "Visa": "V",
    "Johnson & Johnson": "JNJ",
    "Pfizer": "PFE",
    "ExxonMobil": "XOM",
    "ASML": "ASML.AS",
    "SAP": "SAP.DE",
    "Siemens": "SIE.DE",
    "Louis Vuitton (LVMH)": "MC.PA",
    "TotalEnergies": "TTE.PA",
    "Shell": "SHEL.L",
    "Baidu": "BIDU",
    "JD.com": "JD",
    "BYD": "BYDDY",
    "ICBC": "1398.HK",
    "Toyota": "TM",
    "SoftBank": "9984.T",
    "Nintendo": "NTDOY",
    "Hyundai": "005380.KS", #le code HYMTF ne marchait pas c'est le bon code là
    "Reliance Industries": "RELIANCE.NS",
    "Tata Consultancy Services": "TCS.NS",
}

ratios = {
"forwardPE": [],
"beta": [],
"priceToBook": [],

#"priceToSales": [],
"priceToSalesTrailing12Months": [],
"dividendYield": [],
"trailingEps": [],
"debtToEquity": [],
"currentRatio": [],
"quickRatio": [],
"returnOnEquity": [],
"returnOnAssets": [],
"operatingMargins": [],
"profitMargins": []
}

# ─────────────────────────────────────────────────────────────
# FONCTION 1 : Scraping des ratios financiers
# ─────────────────────────────────────────────────────────────

def scrape_financial_ratios(companies: dict = companies,
                             ratio_keys: list = ratios.keys(),
                             output_file: str = "financial_ratios.csv") -> pd.DataFrame:
    """
    Récupère les ratios fondamentaux de chaque entreprise via Yahoo Finance
    et exporte le résultat dans `output_file` (CSV).

    return :
    ---> pd.DataFrame  (index = nom entreprise, colonnes = ratios)
    """
    print("\n[TP1] Scraping des ratios financiers...")

    records = []

    for company_name, symbol in companies.items():
        print(f"  → {company_name} ({symbol})", end=" ")
        row = {"Company": company_name}
        try:
            info = yf.Ticker(symbol).info
            for key in ratio_keys:
                row[key] = info.get(key, None)
            print("✓")
        except Exception as e:
            for key in ratio_keys:
                row[key] = None
            print(f"⚠ {e}")

        records.append(row)
        time.sleep(0.3)   # pause pour recuperer les données de Yahoo Finance

    df = pd.DataFrame(records).set_index("Company")
    df.to_csv(output_file)

    print(f"\n  ✅ Ratios exportés → '{output_file}'")
    return df

# ─────────────────────────────────────────────────────────────
# FONCTION 2 : Scraping de l'historique des cours
# ─────────────────────────────────────────────────────────────

def scrape_historical_prices(companies: dict = companies,
                             output_dir: str = "Companies_historical_data", years: int = 5):
    start_date, end_date = get_date_range(years)
    os.makedirs(output_dir, exist_ok=True)
    results = {}

    for company_name, symbol in companies.items():
        print(f"  → {company_name} ({symbol})", end=" ", flush=True)
        try:
            # Ajout de auto_adjust pour éviter les warnings et avoir des données propres
            raw = yf.download(symbol, start=start_date, end=end_date, progress=False, auto_adjust=True)

            if raw.empty:
                print("⚠ Vide")
                continue

            # Gestion robuste des colonnes (yfinance v0.2.40+)
            if isinstance(raw.columns, pd.MultiIndex):
                df = raw['Close'][[symbol]].copy() # On sélectionne spécifiquement le ticker
                df.columns = ['Close']
            else:
                df = raw[['Close']].copy()

            # ─── MODIFICATION CONSIGNES TP 1 ───
            # 1. Récupérer les données 'Close' de chaque jour [cite: 177] (Fait ci-dessus)

            # 2. Créer une colonne 'Next Day Close' avec la commande shift
            # On utilise shift(-1) pour amener le prix de clôture du lendemain (J+1) sur la ligne d'aujourd'hui
            df['Next Day Close'] = df['Close'].shift(-1)

            # 3. Créer une colonne 'Rendement' qui calcule les variations de stocks d'un jour à l'autre
            df["Rendement"] = (df["Next Day Close"] - df["Close"]) / df["Close"]

            # On enlève la dernière ligne qui contient un NaN (car il n'y a pas de lendemain disponible pour elle)
            df = df.dropna()
            # ────────────────────────────────────

            # Nettoyage nom de fichier plus élégant
            safe_name = "".join([c for c in company_name if c.isalnum() or c in (" ", "_")]).replace(" ", "_")
            filepath = os.path.join(output_dir, f"{safe_name}.csv") # [cite: 180]
            df.to_csv(filepath)

            results[company_name] = df
            print(f"✓ ({len(df)} jours)")

        except Exception as e:
            print(f"⚠ Erreur : {e}")

        time.sleep(0.3)

    return results

#test de l'excecution du tp 1
if __name__ == "__main__":
    scrape_financial_ratios()
    scrape_historical_prices()
