# -*- coding: utf-8 -*-
"""TP2_Clustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OnHdWuo8LQICQUcDjoiX3khsctCfUNHW
"""

# ============================================================
#  TP2 — Clustering sur données financières
#  Fusion des meilleures pratiques des deux versions
# ============================================================

import pandas as pd
import numpy as np
import glob
import os
import warnings
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from matplotlib.colors import ListedColormap
import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans, DBSCAN, AgglomerativeClustering
from sklearn.manifold import TSNE
from sklearn.metrics import silhouette_score
from sklearn.neighbors import NearestNeighbors
from scipy.cluster.hierarchy import linkage, dendrogram, fcluster
from scipy.spatial.distance import squareform

warnings.filterwarnings("ignore")

# ── Chemins ────────────────────────────────────────────────
RATIOS_FILE    = "financial_ratios.csv"
HISTORICAL_DIR = "Companies_historical_data"
PLOTS_DIR      = "plots_tp2"
os.makedirs(PLOTS_DIR, exist_ok=True)

# ── Colonnes utilisées ──────────────────────────────────────
FINANCIAL_COLS = [
    "forwardPE", "priceToBook", "priceToSalesTrailing12Months",
    "returnOnEquity", "returnOnAssets", "profitMargins", "operatingMargins"
]

RISK_COLS = [
    "beta", "debtToEquity", "currentRatio",
    "quickRatio", "returnOnEquity", "dividendYield"
]

# Palette de couleurs vives pour les clusters
CLUSTER_COLORS = ["#4FC3F7", "#81C784", "#FFB74D", "#F06292",
                  "#CE93D8", "#80DEEA", "#FFCC02", "#FF7043"]


# ══════════════════════════════════════════════════════════════
#  UTILITAIRE 1 : Préprocessing robuste aux NA
# ══════════════════════════════════════════════════════════════

def _robust_preprocess(df_sel: pd.DataFrame, label: str):
    """
    Stratégie de nettoyage en 3 étapes :

    Étape 1 — Supprimer les COLONNES avec > 50 % de NA
        Yahoo Finance ne retourne pas certains ratios pour les entreprises
        non-américaines. Si une colonne est vide à 50 %+, elle n'apporte
        pas d'information fiable.

    Étape 2 — Supprimer les LIGNES avec > 50 % de NA restants
        Élimine les entreprises vraiment trop incomplètes.

    Étape 3 — Imputer les NA restants par la MÉDIANE
        On préfère la médiane à la moyenne : les ratios financiers ont des
        distributions très asymétriques (ex. PE de Tesla) qui biaisent
        la moyenne mais pas la médiane.
    """
    n_total = len(df_sel)

    thresh_col   = int(n_total * 0.5)
    df           = df_sel.dropna(axis=1, thresh=thresh_col)
    dropped_cols = set(df_sel.columns) - set(df.columns)
    if dropped_cols:
        print(f"  [{label}] Colonnes retirées (>50% NA) : {dropped_cols}")

    thresh_row = int(df.shape[1] * 0.5)
    df         = df.dropna(axis=0, thresh=thresh_row)
    print(f"  [{label}] {n_total - len(df)} entreprises retirées (>50% NA) "
          f"→ {len(df)} conservées.")

    n_na = df.isnull().sum().sum()
    if n_na > 0:
        df = df.fillna(df.median())
        print(f"  [{label}] {n_na} NA imputés par la médiane.")

    scaler   = StandardScaler()
    X_scaled = scaler.fit_transform(df)
    return X_scaled, df, scaler


# ══════════════════════════════════════════════════════════════
#  UTILITAIRE 2 : Calibration automatique de eps pour DBSCAN
# ══════════════════════════════════════════════════════════════

def _auto_eps(data: np.ndarray, k: int = 4) -> float:
    """
    Calibre eps via la méthode k-distance.

    Pour chaque point, on calcule la distance à son k-ème voisin.
    Le "coude" de la courbe triée représente la frontière naturelle
    entre zones denses (clusters) et zones creuses (bruit).
    """
    k       = min(k, len(data) - 1)
    nbrs    = NearestNeighbors(n_neighbors=k).fit(data)
    dists, _= nbrs.kneighbors(data)
    kdists  = np.sort(dists[:, -1])

    n      = len(kdists)
    coords = np.column_stack([np.arange(n), kdists])
    line   = coords[-1] - coords[0]
    line  /= np.linalg.norm(line)
    dists_to_line = np.abs(np.cross(line, coords[0] - coords))
    elbow_idx     = np.argmax(dists_to_line)
    eps_auto      = float(kdists[elbow_idx])

    print(f"    [eps auto] {eps_auto:.4f} (coude idx {elbow_idx}/{n})")
    return eps_auto


# ══════════════════════════════════════════════════════════════
#  PARTIE 1.1 — FINANCIAL PROFILES CLUSTERING (K-MEANS)
# ══════════════════════════════════════════════════════════════

def preprocess_for_financial_clustering(filepath=RATIOS_FILE, cols=FINANCIAL_COLS):
    df = pd.read_csv(filepath, index_col="Company")
    return _robust_preprocess(df[cols].copy(), "Financial")


def elbow_method(data: np.ndarray, k_max: int = 10, title: str = "Elbow Method"):
    """
    Trace la courbe inertie vs K pour identifier le coude optimal.
    Part de K=1 (référence) jusqu'à k_max.
    """
    inertias = []
    k_range  = range(1, k_max + 1)

    for k in k_range:
        km = KMeans(n_clusters=k, random_state=42, n_init=10)
        km.fit(data)
        inertias.append(km.inertia_)

    # ── Détection automatique du coude ──
    coords = np.column_stack([np.arange(len(inertias)), inertias])
    line   = coords[-1] - coords[0]
    line  /= np.linalg.norm(line)
    dists  = np.abs(np.cross(line, coords[0] - coords))
    best_k = int(np.argmax(dists)) + 1  # +1 car range commence à 1

    fig, ax = plt.subplots(figsize=(9, 5))
    ax.plot(k_range, inertias, "o-", color="#4FC3F7",
            linewidth=2.5, markersize=7, markerfacecolor="white",
            markeredgewidth=2)
    ax.axvline(best_k, color="#FFB74D", linestyle="--",
               linewidth=1.8, label=f"Coude suggéré : K={best_k}")
    ax.set_xlabel("Nombre de clusters K")
    ax.set_ylabel("Inertie intra-cluster")
    ax.set_title(title)
    ax.legend()
    ax.grid(True)
    plt.tight_layout()
    plt.savefig(os.path.join(PLOTS_DIR, f"elbow_{title.replace(' ','_')}.png"),
                dpi=150, bbox_inches="tight")
    plt.show()

    print(f"  [Elbow] Coude détecté automatiquement à K={best_k}")
    return inertias


def do_kmeans_clustering(data, df_clean, n_clusters, label="financial"):
    km     = KMeans(n_clusters=n_clusters, random_state=42, n_init=10)
    labels = km.fit_predict(data)

    df_result = df_clean.copy()
    df_result["Cluster"] = labels

    print(f"\n  Profil moyen par cluster ({label}) :")
    print(df_result.groupby("Cluster").mean().round(3).to_string())

    # ── t-SNE ──────────────────────────────────────────────
    perplexity = min(30, len(data) - 1)
    coords = TSNE(n_components=2, perplexity=perplexity,
                  random_state=42, init="pca",
                  learning_rate="auto").fit_transform(data)

    colors = [CLUSTER_COLORS[i % len(CLUSTER_COLORS)] for i in range(n_clusters)]

    fig, ax = plt.subplots(figsize=(12, 8))

    for k in range(n_clusters):
        mask = labels == k
        ax.scatter(coords[mask, 0], coords[mask, 1],
                   color=colors[k], s=90, alpha=0.9,
                   edgecolors="white", linewidths=0.4,
                   label=f"Cluster {k} ({mask.sum()} entreprises)")

    for i, name in enumerate(df_clean.index):
        ax.annotate(name,
                    xy=(coords[i, 0], coords[i, 1]),
                    xytext=(6, 4), textcoords="offset points",
                    fontsize=7, alpha=0.85, color="#d0d0d0")

    ax.legend(title="Clusters", loc="best", framealpha=0.8)
    ax.set_title(f"K-Means ({n_clusters} clusters) — {label} — t-SNE")
    ax.set_xlabel("t-SNE dim 1")
    ax.set_ylabel("t-SNE dim 2")
    plt.tight_layout()
    plt.savefig(os.path.join(PLOTS_DIR, f"kmeans_tsne_{label}.png"),
                dpi=150, bbox_inches="tight")
    plt.show()

    return df_result, labels


# ══════════════════════════════════════════════════════════════
#  PARTIE 1.2 — RISK PROFILES CLUSTERING (HIERARCHICAL)
# ══════════════════════════════════════════════════════════════

def preprocess_for_risk_clustering(filepath=RATIOS_FILE, cols=RISK_COLS):
    df = pd.read_csv(filepath, index_col="Company")
    return _robust_preprocess(df[cols].copy(), "Risk")


def plot_dendrogram(data, df_clean, k_suggestion=4, label="risk"):
    """
    Trace le dendrogramme avec :
    - une ligne de coupe visuelle (comme Code 2, très pédagogique)
    - coloration automatique des branches (comme Code 1)
    """
    linked    = linkage(data, method="ward")
    distances = linked[:, 2]

    # Seuil de coupe entre les deux derniers sauts de distance
    threshold = (distances[-k_suggestion] + distances[-k_suggestion + 1]) / 2

    fig, ax = plt.subplots(figsize=(16, 7))
    dendrogram(linked,
               labels=list(df_clean.index),
               leaf_rotation=90,
               leaf_font_size=8,
               color_threshold=threshold,
               ax=ax)

    ax.axhline(y=threshold, color="#FFB74D", linestyle="--",
               linewidth=1.8, label=f"Coupe → K={k_suggestion} clusters")
    ax.set_title(f"Dendrogramme — Clustering hiérarchique ({label})")
    ax.set_xlabel("Entreprises")
    ax.set_ylabel("Distance (Ward)")
    ax.legend()
    plt.tight_layout()
    plt.savefig(os.path.join(PLOTS_DIR, f"dendrogram_{label}.png"),
                dpi=150, bbox_inches="tight")
    plt.show()

    return linked


def do_hierarchical_clustering(data, df_clean, n_clusters=4, label="risk"):
    labels = AgglomerativeClustering(
        n_clusters=n_clusters, linkage="ward"
    ).fit_predict(data)

    df_result = df_clean.copy()
    df_result["Cluster"] = labels

    print(f"\n  Profil moyen par cluster ({label}) :")
    print(df_result.groupby("Cluster").mean().round(3).to_string())

    # ── Heatmap des profils de risque par cluster ───────────
    profile_means = df_result.groupby("Cluster").mean()

    fig, ax = plt.subplots(figsize=(10, 5))
    sns.heatmap(profile_means.T,
                annot=True, fmt=".2f", cmap="RdYlGn",
                linewidths=0.5, linecolor="#0f1117",
                cbar_kws={"label": "Valeur moyenne"},
                ax=ax)
    ax.set_title(f"Profils moyens par cluster — {label}")
    ax.set_ylabel("Variables")
    ax.set_xlabel("Cluster")
    plt.tight_layout()
    plt.savefig(os.path.join(PLOTS_DIR, f"heatmap_clusters_{label}.png"),
                dpi=150, bbox_inches="tight")
    plt.show()

    return df_result, labels


# ══════════════════════════════════════════════════════════════
#  PARTIE 1.3 — DAILY RETURNS CORRELATIONS CLUSTERING
# ══════════════════════════════════════════════════════════════

def load_daily_returns(historical_dir=HISTORICAL_DIR):
    if not os.path.exists(historical_dir):
        raise FileNotFoundError(
            f"Dossier introuvable : '{historical_dir}'\n"
            f"  → Répertoire courant : {os.getcwd()}"
        )
    filepaths = glob.glob(os.path.join(historical_dir, "*.csv"))
    if not filepaths:
        raise FileNotFoundError(
            f"Aucun CSV dans '{historical_dir}'"
        )

    returns_dict = {}
    for fp in filepaths:
        name = os.path.basename(fp).replace(".csv", "").replace("_", " ")
        df   = pd.read_csv(fp, index_col="Date", parse_dates=True)
        col  = "Rendement" if "Rendement" in df.columns else df.columns[-1]
        returns_dict[name] = df[col]

    returns_df = pd.DataFrame(returns_dict)
    # Médiane (plus robuste aux outliers de marché que la moyenne)
    returns_df = returns_df.fillna(returns_df.median())
    print(f"  [Returns] {returns_df.shape[1]} entreprises, "
          f"{returns_df.shape[0]} jours chargés.")
    return returns_df


def cluster_by_correlation(returns_df, n_clusters=5):
    """
    ⚠️  POINT CLÉ : on convertit la matrice de corrélation en matrice de
    DISTANCES (dist = 1 - corr) avant d'appliquer linkage/Ward.
    Linkage attend des distances, pas des similarités.
    """
    corr_matrix = returns_df.corr()

    # Conversion correcte corrélation → distance
    dist_matrix = np.clip(1 - corr_matrix.values, 0, None)
    linked      = linkage(squareform(dist_matrix), method="ward")

    # ── Dendrogramme avec ligne de coupe ───────────────────
    distances = linked[:, 2]
    threshold = (distances[-n_clusters] + distances[-n_clusters + 1]) / 2

    fig, ax = plt.subplots(figsize=(18, 7))
    dendrogram(linked,
               labels=list(corr_matrix.index),
               leaf_rotation=90, leaf_font_size=7,
               color_threshold=threshold,
               ax=ax)
    ax.axhline(y=threshold, color="#FFB74D", linestyle="--",
               linewidth=1.8, label=f"Coupe → K={n_clusters} clusters")
    ax.set_title("Dendrogramme — Clustering par corrélations de rendements")
    ax.set_xlabel("Entreprises")
    ax.set_ylabel("Distance (1 − corrélation, Ward)")
    ax.legend()
    plt.tight_layout()
    plt.savefig(os.path.join(PLOTS_DIR, "dendrogram_returns.png"),
                dpi=150, bbox_inches="tight")
    plt.show()

    # ── Heatmap de corrélation triée par cluster ────────────
    cluster_labels = fcluster(linked, t=n_clusters, criterion="maxclust")
    order = np.argsort(cluster_labels)
    corr_sorted = corr_matrix.iloc[order, order]

    fig, ax = plt.subplots(figsize=(16, 13))
    sns.heatmap(corr_sorted,
                cmap="RdYlGn", vmin=-1, vmax=1,
                xticklabels=corr_sorted.columns,
                yticklabels=corr_sorted.columns,
                linewidths=0, ax=ax,
                cbar_kws={"label": "Corrélation"})
    ax.set_xticklabels(ax.get_xticklabels(), rotation=90, fontsize=6)
    ax.set_yticklabels(ax.get_yticklabels(), rotation=0, fontsize=6)
    ax.set_title("Matrice de corrélation des rendements (triée par cluster)")
    plt.tight_layout()
    plt.savefig(os.path.join(PLOTS_DIR, "heatmap_correlation.png"),
                dpi=150, bbox_inches="tight")
    plt.show()

    df_result = pd.DataFrame({
        "Company": corr_matrix.index,
        "Cluster": cluster_labels
    }).set_index("Company")

    return df_result, corr_matrix


# ══════════════════════════════════════════════════════════════
#  PARTIE 1.4 — DBSCAN + ÉVALUATION COMPARATIVE
# ══════════════════════════════════════════════════════════════

def do_dbscan_clustering(data, df_clean, eps=None, min_samples=3, label="", plot=True):
    """
    DBSCAN avec calibration automatique d'eps (méthode k-distance).
    """
    if eps is None:
        eps = _auto_eps(data, k=min(4, len(data) - 1)) * 0.7

    labels = DBSCAN(eps=eps, min_samples=min_samples).fit_predict(data)

    df_result = df_clean.copy()
    df_result["Cluster"] = labels

    n_clusters = len(set(labels)) - (1 if -1 in labels else 0)
    n_noise    = list(labels).count(-1)

    print(f"\n  [DBSCAN {label}] eps={eps:.4f}, min_samples={min_samples}")
    print(f"  → {n_clusters} clusters | {n_noise} points bruit")

    if n_clusters > 0:
        cc = (df_result[df_result["Cluster"] != -1]["Cluster"]
              .value_counts().sort_index())
        for c_id, count in cc.items():
            print(f"     Cluster {c_id} : {count} entreprises")

    return df_result, labels


# ── Visualisation t-SNE commune aux 3 datasets DBSCAN ──────────

def _plot_dbscan_tsne(data, df_clean, labels, eps, min_samples, label):
    """t-SNE uniforme pour les 3 datasets, outliers en croix grises."""
    perplexity = min(30, len(data) - 1)
    coords = TSNE(n_components=2, perplexity=perplexity,
                  random_state=42, init="pca",
                  learning_rate="auto").fit_transform(data)

    n_noise = (labels == -1).sum()
    noise_pct = 100 * n_noise / len(labels)

    unique_labels = sorted(set(labels))
    fig, ax = plt.subplots(figsize=(12, 8))

    for k in unique_labels:
        mask  = labels == k
        color = "#888888" if k == -1 else CLUSTER_COLORS[k % len(CLUSTER_COLORS)]
        lname = (f"Bruit — outliers ({mask.sum()} -> {noise_pct:.0f}%)"
                 if k == -1 else f"Cluster {k} ({mask.sum()})")
        ax.scatter(coords[mask, 0], coords[mask, 1],
                   color=color, s=90 if k != -1 else 50,
                   alpha=0.85 if k != -1 else 0.4,
                   edgecolors="white" if k != -1 else "none",
                   linewidths=0.4, label=lname,
                   marker="o" if k != -1 else "x")

    for i, name in enumerate(df_clean.index):
        ax.annotate(name, xy=(coords[i, 0], coords[i, 1]),
                    xytext=(6, 4), textcoords="offset points",
                    fontsize=7, alpha=0.8, color="#d0d0d0")

    ax.legend(title="DBSCAN", loc="best", framealpha=0.8)
    ax.set_title(f"DBSCAN — {label} — t-SNE\n"
                 f"eps={eps:.3f}, min_samples={min_samples}")
    ax.set_xlabel("t-SNE dim 1")
    ax.set_ylabel("t-SNE dim 2")
    plt.tight_layout()
    plt.savefig(os.path.join(PLOTS_DIR, f"dbscan_tsne_{label}.png"),
                dpi=150, bbox_inches="tight")
    plt.show()


def _silhouette_safe(data, labels, noise_threshold=0.5):
    """
    Calcule le silhouette score DBSCAN de façon honnête.

    Règle anti-biais : si plus de `noise_threshold` (défaut 50%) des points
    sont marqués bruit (-1), on retourne N/A.

    Pourquoi ? Avec 37/41 outliers, le score est calculé sur 4 points
    formant un micro-cluster parfait → score artificiellement élevé
    qui ne reflète pas la qualité réelle du clustering.
    """
    n_noise     = (labels == -1).sum()
    noise_ratio = n_noise / len(labels)

    if noise_ratio > noise_threshold:
        print(f"  ⚠️  Silhouette N/A : {n_noise}/{len(labels)} points "
              f"({noise_ratio:.0%}) en bruit → score biaisé, ignoré.")
        return np.nan

    mask = labels != -1
    if len(set(labels[mask])) < 2:
        return np.nan

    return round(silhouette_score(data[mask], labels[mask]), 4)


def _dbscan_with_fallback(data, label="", noise_threshold=0.5):
    """
    Cherche les paramètres DBSCAN maximisant le silhouette score
    sous contrainte : taux de bruit ≤ noise_threshold.

    On explore une grille (factor × eps_auto, min_samples).
    Cela évite de retenir une solution qui "triche" en mettant
    presque tout le monde en bruit pour scorer haut sur 3 points.
    """
    base_eps   = _auto_eps(data, k=min(4, len(data) - 1))
    best_score = -2.0
    best_labels, best_params = None, None

    for factor in [1.0, 0.9, 0.75, 0.6, 0.5, 0.4, 0.3]:
        for ms in [3, 2]:
            eps_try     = base_eps * factor
            lbl         = DBSCAN(eps=eps_try, min_samples=ms).fit_predict(data)
            noise_ratio = (lbl == -1).sum() / len(lbl)
            mask        = lbl != -1

            # On rejette les solutions avec trop de bruit
            if noise_ratio > noise_threshold:
                continue
            if len(set(lbl[mask])) < 2:
                continue

            score = silhouette_score(data[mask], lbl[mask])
            if score > best_score:
                best_score  = score
                best_labels = lbl
                best_params = (eps_try, ms)

    if best_labels is None:
        print(f"  [DBSCAN {label}] ⚠️  Aucun paramètre valide avec ≤{noise_threshold:.0%} bruit.")
        best_labels = np.full(len(data), -1)
        best_params = (base_eps, 3)
    else:
        n_noise = (best_labels == -1).sum()
        print(f"  [DBSCAN {label}] ✅ eps={best_params[0]:.4f}, "
              f"min_samples={best_params[1]} | silhouette={best_score:.4f} | "
              f"bruit={n_noise}/{len(data)} ({n_noise/len(data):.0%})")

    return best_labels, best_params


def evaluate_all_algorithms(X_fin, X_risk, returns_df, corr_matrix,
                            n_clusters_financial=4,
                            n_clusters_risk=4,
                            n_clusters_returns=5,
                            noise_threshold=0.5):
    """
    Compare K-Means, Hierarchical et DBSCAN sur les 3 datasets.

    Anti-biais DBSCAN : on rejette tout paramétrage où >50% des points
    sont en bruit (-1), car le silhouette score serait calculé sur un
    sous-ensemble trop petit et donnerait un score artificiellement élevé.
    """
    print("\n[TP2] Évaluation comparative...\n")

    X_ret = StandardScaler().fit_transform(returns_df.T.values)
    df_ret_dummy = pd.DataFrame(index=returns_df.columns)

    _, df_fin_clean, _ = preprocess_for_financial_clustering()
    _, df_risk_clean, _= preprocess_for_risk_clustering()

    datasets = {
        "Financial": (X_fin,  n_clusters_financial, df_fin_clean),
        "Risk":      (X_risk, n_clusters_risk,       df_risk_clean),
        "Returns":   (X_ret,  n_clusters_returns,    df_ret_dummy),
    }

    results     = {}
    dbscan_runs = {}

    for ds, (X, k, df_clean) in datasets.items():
        km_labels   = KMeans(k, random_state=42, n_init=10).fit_predict(X)
        hier_labels = AgglomerativeClustering(k, linkage="ward").fit_predict(X)
        db_labels, db_params = _dbscan_with_fallback(
            X, label=ds, noise_threshold=noise_threshold
        )
        dbscan_runs[ds] = (X, df_clean, db_labels, db_params)

        results[ds] = {
            "K-Means":      _silhouette_safe(X, km_labels),
            "Hierarchical": _silhouette_safe(X, hier_labels),
            "DBSCAN":       _silhouette_safe(X, db_labels,
                                             noise_threshold=noise_threshold),
        }

    # ── t-SNE pour les 3 datasets DBSCAN ───────────────────
    print("\n  [DBSCAN] Visualisations t-SNE des 3 datasets...\n")
    for ds, (X, df_clean, db_labels, (eps, ms)) in dbscan_runs.items():
        _plot_dbscan_tsne(X, df_clean, db_labels, eps, ms, label=ds)

    df_scores = pd.DataFrame(results).T
    df_scores.index.name = "Dataset"

    # ── Tableau avec fond blanc ─────────────────────────────
    df_display = df_scores.copy().astype(object)
    df_display = df_display.where(df_scores.notna(), other="N/A")

    fig, ax = plt.subplots(figsize=(8, 3.5))
    ax.axis("off")
    fig.patch.set_facecolor("white")

    cell_colors = []
    for row in df_scores.itertuples(index=False):
        row_colors = []
        values = [v for v in row if isinstance(v, float) and not np.isnan(v)]
        best   = max(values) if values else None
        for v in row:
            if isinstance(v, float) and not np.isnan(v) and v == best:
                row_colors.append("#c8e6c9")   # vert clair = meilleur
            elif not isinstance(v, float) or np.isnan(v):
                row_colors.append("#ffcdd2")   # rouge clair = N/A
            else:
                row_colors.append("#ffffff")   # blanc = valeur normale
        cell_colors.append(row_colors)

    tbl = ax.table(
        cellText=df_display.values.tolist(),
        rowLabels=df_scores.index,
        colLabels=df_scores.columns,
        cellLoc="center", loc="center",
        cellColours=cell_colors,
    )
    tbl.auto_set_font_size(False)
    tbl.set_fontsize(11)
    tbl.scale(1.4, 2.0)

    for (r, c), cell in tbl.get_celld().items():
        cell.set_edgecolor("#cccccc")
        if r == 0 or c == -1:
            cell.set_facecolor("#1565c0")
            cell.set_text_props(color="white", fontweight="bold")
        else:
            cell.set_text_props(color="#212121")

    ax.set_title("Silhouette Scores — Comparaison des algorithmes\n"
                 "(vert = meilleur score par ligne, rouge = N/A)",
                 pad=15, color="#212121", fontsize=12)
    plt.tight_layout()
    plt.savefig(os.path.join(PLOTS_DIR, "silhouette_scores_table.png"),
                dpi=150, bbox_inches="tight")
    plt.show()

    print("\n  ── Silhouette Scores ──")
    print(df_display.to_string())
    df_scores.to_csv("silhouette_scores.csv")
    return df_scores


# ══════════════════════════════════════════════════════════════
#  POINT D'ENTRÉE
# ══════════════════════════════════════════════════════════════

def run_tp2():
    print("\n" + "=" * 60)
    print("  TP2 — CLUSTERING SUR DONNÉES FINANCIÈRES")
    print("=" * 60)

    # ── 1.1 Financial ───────────────────────────────────────
    print("\n[1.1] Financial Profiles — K-Means")
    X_fin, df_fin, _ = preprocess_for_financial_clustering()
    elbow_method(X_fin, k_max=10, title="Financial Profiles")
    K_FIN = 4   # ← Ajuster selon le coude observé
    df_fin_result, _ = do_kmeans_clustering(X_fin, df_fin, K_FIN, "financial")

    # ── 1.2 Risk ────────────────────────────────────────────
    print("\n[1.2] Risk Profiles — Hierarchical Clustering")
    X_risk, df_risk, _ = preprocess_for_risk_clustering()
    K_RISK = 4  # ← Ajuster selon le dendrogramme
    plot_dendrogram(X_risk, df_risk, k_suggestion=K_RISK, label="risk")
    df_risk_result, _ = do_hierarchical_clustering(X_risk, df_risk, K_RISK, "risk")

    # ── 1.3 Returns ─────────────────────────────────────────
    print("\n[1.3] Daily Returns Correlations")
    returns_df = load_daily_returns()
    df_ret_result, corr_matrix = cluster_by_correlation(returns_df, n_clusters=5)

    # ── 1.4 Évaluation comparative ──────────────────────────
    print("\n[1.4] Évaluation comparative — Silhouette Scores")
    df_scores = evaluate_all_algorithms(
        X_fin, X_risk, returns_df, corr_matrix, K_FIN, K_RISK
    )

    print("\n✅ TP2 terminé — graphiques sauvegardés dans :", PLOTS_DIR)
    return {
        "financial_clusters": df_fin_result,
        "risk_clusters":      df_risk_result,
        "returns_clusters":   df_ret_result,
        "silhouette_scores":  df_scores,
        "correlation_matrix": corr_matrix,
    }


if __name__ == "__main__":
    run_tp2()
