# -*- coding: utf-8 -*-
"""TP3_classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k4ol_KNImZBWjL_GFccsFITXsqy-cFns
"""

# ============================================================
#  TP3 — Classification des Signaux Boursiers (Buy/Hold/Sell)
#  Architecture de Production (Basée sur les Best Practices V2)
# ============================================================

import os
import glob
import warnings
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import shap

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report
from imblearn.over_sampling import SMOTE

from ta.trend import SMAIndicator, EMAIndicator, MACD
from ta.momentum import RSIIndicator, ROCIndicator
from ta.volatility import BollingerBands

from lightgbm import LGBMClassifier
from xgboost import XGBClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

warnings.filterwarnings("ignore")

# ── Chemins et Constantes ──────────────────────────────────
HISTORICAL_DIR = "Companies_historical_data"
PLOTS_DIR      = "plots_tp3"
os.makedirs(PLOTS_DIR, exist_ok=True)


# =====================================================================
#  1. PRÉ-TRAITEMENT ET FEATURE ENGINEERING (STATIONNAIRE)
# =====================================================================

def preprocess_single_company(file_path):
    """
    Calcule les indicateurs techniques et génère les labels (Buy/Hold/Sell).
    Génère des features 100% stationnaires (ratios).
    """
    df = pd.read_csv(file_path, index_col=0)
    df.index = pd.to_datetime(df.index)
    company_returns = df[['Close']].copy()

    # Logique d'horizon et labels (J+20)
    company_returns['Close_Horizon'] = company_returns['Close'].shift(-20)
    company_returns['horizon_return'] = (company_returns['Close_Horizon'] - company_returns['Close']) / company_returns['Close']

    conditions = [
        (company_returns['horizon_return'] > 0.05),
        (company_returns['horizon_return'] < -0.05)
    ]
    # 2: Buy, 0: Sell, 1: Hold
    company_returns['label'] = np.select(conditions, [2, 0], default=1)

    # Indicateurs bruts
    sma_20 = SMAIndicator(close=company_returns['Close'], window=20).sma_indicator()
    ema_20 = EMAIndicator(close=company_returns['Close'], window=20).ema_indicator()
    macd_obj = MACD(close=company_returns['Close'])
    bb = BollingerBands(close=company_returns['Close'])

    # Features stationnaires (Ratios, Oscillateurs)
    company_returns['RSI_14'] = RSIIndicator(close=company_returns['Close'], window=14).rsi()
    company_returns['ROC_10'] = ROCIndicator(close=company_returns['Close'], window=10).roc()
    company_returns['Volatility_20'] = company_returns['Close'].pct_change().rolling(window=20).std()

    company_returns['price_vs_sma'] = company_returns['Close'] / sma_20
    company_returns['price_vs_ema'] = company_returns['Close'] / ema_20
    company_returns['bollinger_pct'] = (company_returns['Close'] - bb.bollinger_lband()) / (bb.bollinger_hband() - bb.bollinger_lband())
    company_returns['macd_norm'] = macd_obj.macd() / company_returns['Close']
    company_returns['macd_sig_norm'] = macd_obj.macd_signal() / company_returns['Close']
    company_returns['month'] = company_returns.index.month

    return company_returns.dropna()


def build_global_pipeline(folder_path=HISTORICAL_DIR):
    """ Compile toutes les entreprises, nettoie les prix absolus et standardise. """
    files = glob.glob(os.path.join(folder_path, "*.csv"))
    all_dfs = []

    for f in files:
        try:
            all_dfs.append(preprocess_single_company(f))
        except Exception as e:
            print(f"Erreur sur {f}: {e}")

    if not all_dfs:
        raise ValueError(f"Aucun DataFrame chargé depuis {folder_path}.")

    df_global = pd.concat(all_dfs, axis=0)
    print(f"[Pipeline] Dataset combiné : {df_global.shape[0]} lignes, {df_global.shape[1]} colonnes.")

    Y = df_global['label']

    # Nettoyage strict : suppression des prix absolus et variables de calcul
    cols_to_drop = ['label', 'Close', 'Close_Horizon', 'horizon_return', 'Weekly return', 'Next Day Close']
    X = df_global.drop(columns=[c for c in cols_to_drop if c in df_global.columns])

    # Standardisation
    X_scaled = pd.DataFrame(StandardScaler().fit_transform(X), columns=X.columns)

    X_train, X_test, y_train, y_test = train_test_split(
        X_scaled, Y, test_size=0.2, random_state=42, stratify=Y
    )

    print(f"[Pipeline] Distribution Train :\n{y_train.value_counts().sort_index().to_dict()}")
    return X_train, X_test, y_train, y_test


# =====================================================================
#  2. ENTRAÎNEMENT ET ÉVALUATION
# =====================================================================

def train_and_evaluate(model, param_grid, X_train, X_test, y_train, y_test, model_name):
    """ Gère le GridSearch, l'évaluation et la génération des SHAP values. """
    print(f"\n{'='*50}\n Entraînement : {model_name}\n{'='*50}")

    grid_search = GridSearchCV(estimator=model, param_grid=param_grid, cv=3, scoring='accuracy', n_jobs=-1)
    grid_search.fit(X_train, y_train)
    best_model = grid_search.best_estimator_

    print(f"Meilleurs paramètres : {grid_search.best_params_}")

    y_pred = best_model.predict(X_test)
    report_dict = classification_report(y_test, y_pred, output_dict=True, zero_division=0)
    print(classification_report(y_test, y_pred, target_names=['Sell (0)', 'Hold (1)', 'Buy (2)'], zero_division=0))

    # SHAP (uniquement pour modèles basés sur les arbres pour des raisons de performance)
    if model_name in ["Random Forest", "XGBoost", "LightGBM"]:
        print(f"Génération SHAP pour {model_name}...")
        try:
            explainer = shap.TreeExplainer(best_model)
            shap_values = explainer.shap_values(X_test)

            # Gestion des différences de format SHAP selon les modèles
            shap_sell = shap_values[0] if isinstance(shap_values, list) else shap_values[:, :, 0]
            shap_buy  = shap_values[2] if isinstance(shap_values, list) else shap_values[:, :, 2]

            plt.figure(figsize=(10, 6))
            shap.summary_plot(shap_sell, X_test, feature_names=X_test.columns, show=False)
            plt.title(f"SHAP - Prédiction 'Sell' ({model_name})")
            plt.tight_layout()
            plt.savefig(os.path.join(PLOTS_DIR, f"shap_sell_{model_name.replace(' ','_')}.png"))
            plt.close()

            plt.figure(figsize=(10, 6))
            shap.summary_plot(shap_buy, X_test, feature_names=X_test.columns, show=False)
            plt.title(f"SHAP - Prédiction 'Buy' ({model_name})")
            plt.tight_layout()
            plt.savefig(os.path.join(PLOTS_DIR, f"shap_buy_{model_name.replace(' ','_')}.png"))
            plt.close()
            print("Graphiques SHAP sauvegardés.")
        except Exception as e:
            print(f"⚠️ SHAP échoué pour {model_name} : {e}")

    return best_model, report_dict


# =====================================================================
#  3. DÉFINITION DES MODÈLES (AVEC GESTION DU DÉSÉQUILIBRE)
# =====================================================================

def run_all_models(X_train, X_test, y_train, y_test):
    reports = {}
    best_models = {}

    # Outil SMOTE pour les modèles ne gérant pas 'class_weight'
    smote = SMOTE(random_state=42)
    X_train_res, y_train_res = smote.fit_resample(X_train, y_train)

    # 1. Random Forest (gère class_weight)
    m_rf, r_rf = train_and_evaluate(
        RandomForestClassifier(random_state=42, class_weight='balanced'),
        {'n_estimators': [50, 100], 'max_depth': [10, 15]},
        X_train, X_test, y_train, y_test, "Random Forest"
    )
    reports["Random Forest"], best_models["Random Forest"] = r_rf, m_rf

    # 2. XGBoost (nécessite SMOTE)
    m_xgb, r_xgb = train_and_evaluate(
        XGBClassifier(random_state=42, eval_metric='mlogloss'),
        {'n_estimators': [50, 100], 'learning_rate': [0.1], 'max_depth': [5, 7]},
        X_train_res, X_test, y_train_res, y_test, "XGBoost"
    )
    reports["XGBoost"], best_models["XGBoost"] = r_xgb, m_xgb

    # 3. LightGBM (gère class_weight)
    m_lgb, r_lgb = train_and_evaluate(
        LGBMClassifier(class_weight='balanced', random_state=42, n_jobs=-1, verbose=-1),
        {'n_estimators': [50, 100], 'learning_rate': [0.05, 0.1], 'max_depth': [5, 7]},
        X_train, X_test, y_train, y_test, "LightGBM"
    )
    reports["LightGBM"], best_models["LightGBM"] = r_lgb, m_lgb

    # 4. Régression Logistique (gère class_weight)
    m_log, r_log = train_and_evaluate(
        LogisticRegression(random_state=42, class_weight='balanced'),
        {'C': [0.1, 1.0], 'solver': ['lbfgs'], 'max_iter': [1000]},
        X_train, X_test, y_train, y_test, "Logistic Regression"
    )
    reports["Logistic Regression"] = r_log

    return reports, best_models


# =====================================================================
#  4. SYNTHÈSE DES RÉSULTATS
# =====================================================================

def generate_summary_table(reports_dict):
    """ Extrait les métriques clés pour comparaison """
    rows = []
    for model_name, report in reports_dict.items():
        key_sell = next((k for k in report.keys() if '0' in str(k)), None)
        key_hold = next((k for k in report.keys() if '1' in str(k)), None)
        key_buy  = next((k for k in report.keys() if '2' in str(k)), None)

        rows.append({
            "Modèle": model_name,
            "Accuracy": round(report.get("accuracy", 0), 2),
            "Prec_Buy": round(report[key_buy]["precision"], 2) if key_buy else 0,
            "Rec_Buy": round(report[key_buy]["recall"], 2) if key_buy else 0,
            "Prec_Sell": round(report[key_sell]["precision"], 2) if key_sell else 0,
            "Rec_Sell": round(report[key_sell]["recall"], 2) if key_sell else 0,
            "F1_Hold": round(report[key_hold]["f1-score"], 2) if key_hold else 0,
        })

    df_res = pd.DataFrame(rows).sort_values(by="Accuracy", ascending=False)
    return df_res


# =====================================================================
#  POINT D'ENTRÉE PRINCIPAL
# =====================================================================

def run_tp3():
    print("\n" + "="*60 + "\n LANCEMENT DU TP3 - CLASSIFICATION\n" + "="*60)

    # 1. Pipeline de données
    X_train, X_test, y_train, y_test = build_global_pipeline()

    # 2. Entraînement et évaluation
    reports, models = run_all_models(X_train, X_test, y_train, y_test)

    # 3. Tableau de synthèse
    df_final = generate_summary_table(reports)
    print("\n" + "="*50 + "\n TABLEAU COMPARATIF FINAL\n" + "="*50)
    print(df_final.to_string(index=False))
    df_final.to_csv(os.path.join(PLOTS_DIR, "model_comparison.csv"), index=False)

    # 4. Feature Importances du meilleur modèle (Random Forest)
    if "Random Forest" in models:
        print("\n--- Top 10 Features (Random Forest) ---")
        importances = pd.Series(models["Random Forest"].feature_importances_, index=X_train.columns)
        print(importances.sort_values(ascending=False).head(10))

    print(f"\n✅ TP3 terminé. Les graphiques SHAP et rapports sont dans '{PLOTS_DIR}/'.")

    return models, df_final

if __name__ == "__main__":
    run_tp3()
