# -*- coding: utf-8 -*-
"""TP4_regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A5M23JTR2g5TlKKI4P7VLdukA27L7s2c
"""

# ============================================================
#  TP4 — Prédiction des Prix (Régression Multivariée)
#  Architecture de Production — Version Automatique Globale
# ============================================================

import os
import glob
import warnings
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor

from ta.trend import SMAIndicator, EMAIndicator, MACD
from ta.momentum import RSIIndicator, ROCIndicator
from ta.volatility import BollingerBands

warnings.filterwarnings("ignore")

# ── Chemins et Constantes ──────────────────────────────────
HISTORICAL_DIR = "Companies_historical_data"
PLOTS_DIR      = "plots_tp4"
os.makedirs(PLOTS_DIR, exist_ok=True)


# =====================================================================
#  1. PRÉPARATION DES DONNÉES ET FEATURE ENGINEERING
# =====================================================================

def prepare_regression_data(file_path, n_days=30, test_size=0.2):
    """
    Prépare les séquences de 30 jours (Close) + Features stationnaires du jour J.
    """
    df = pd.read_csv(file_path, index_col=0)
    df.index = pd.to_datetime(df.index)
    df = df.sort_index()
    df = df[['Close']].copy()

    # --- Features stationnaires ---
    sma_20      = SMAIndicator(close=df['Close'], window=20).sma_indicator()
    ema_20      = EMAIndicator(close=df['Close'], window=20).ema_indicator()
    macd_obj    = MACD(close=df['Close'])
    macd_raw    = macd_obj.macd()
    macd_signal = macd_obj.macd_signal()
    bb          = BollingerBands(close=df['Close'])
    bb_high     = bb.bollinger_hband()
    bb_low      = bb.bollinger_lband()
    bb_range    = bb_high - bb_low

    df['RSI_14']                 = RSIIndicator(close=df['Close'], window=14).rsi()
    df['ROC_10']                 = ROCIndicator(close=df['Close'], window=10).roc()
    df['Rolling_Volatility_20']  = df['Close'].pct_change().rolling(20).std()
    df['price_vs_sma']           = df['Close'] / sma_20
    df['price_vs_ema']           = df['Close'] / ema_20
    df['bollinger_pct']          = np.where(bb_range != 0, (df['Close'] - bb_low) / bb_range, 0.5)
    df['macd_normalized']        = macd_raw    / df['Close']
    df['macd_signal_normalized'] = macd_signal / df['Close']
    df['month']                  = df.index.month
    df = df.dropna()

    # --- Séparation Temporelle Stricte ---
    split_idx = int(len(df) * (1 - test_size))
    train_df  = df.iloc[:split_idx]
    test_df   = df.iloc[split_idx:]

    # --- Scalers Indépendants ---
    feature_cols = [c for c in df.columns if c != 'Close']
    scaler_close    = MinMaxScaler()
    scaler_features = MinMaxScaler()

    train_close_scaled    = scaler_close.fit_transform(train_df[['Close']])
    train_features_scaled = scaler_features.fit_transform(train_df[feature_cols])
    test_close_scaled     = scaler_close.transform(test_df[['Close']])
    test_features_scaled  = scaler_features.transform(test_df[feature_cols])

    # --- Création des Séquences (Fenêtres Glissantes) ---
    def create_sequences(close_scaled, features_scaled, n):
        X, Y = [], []
        for i in range(n, len(close_scaled)):
            window_close  = close_scaled[i-n:i].flatten()  # 30 jours de Close
            current_feats = features_scaled[i]             # Features du jour J
            X.append(np.concatenate([window_close, current_feats]))
            Y.append(close_scaled[i, 0])                   # Close à J+1
        return np.array(X), np.array(Y)

    X_train, y_train = create_sequences(train_close_scaled, train_features_scaled, n_days)
    X_test,  y_test  = create_sequences(test_close_scaled,  test_features_scaled,  n_days)

    y_test_raw = test_df['Close'].iloc[n_days:].values

    return X_train, X_test, y_train, y_test, scaler_close, y_test_raw


# =====================================================================
#  2. ENTRAÎNEMENT ET ÉVALUATION
# =====================================================================

def run_regression_pipeline(X_train, X_test, y_train, y_test, scaler_close, y_test_raw, company_name):
    """
    Entraîne, optimise et évalue les modèles de régression.
    """
    print(f"\n▶️ Optimisation et Entraînement pour : {company_name}...")

    all_predictions = {}
    performance_records = []
    trained_models = {}

    models_config = {
        "Régression Linéaire": {"model": LinearRegression(), "params": {}},
        "Random Forest": {
            "model": RandomForestRegressor(random_state=42, n_jobs=-1),
            "params": {'n_estimators': [50, 100], 'max_depth': [5, 10]}
        },
        "KNN": {
            "model": KNeighborsRegressor(),
            "params": {'n_neighbors': [5, 7], 'weights': ['uniform', 'distance']}
        },
        "XGBoost": {
            "model": XGBRegressor(random_state=42, eval_metric='rmse', n_jobs=-1),
            "params": {'n_estimators': [50, 100], 'learning_rate': [0.1], 'max_depth': [3, 5]}
        },
        "LightGBM": {
            "model": LGBMRegressor(random_state=42, n_jobs=-1, verbose=-1),
            "params": {'n_estimators': [100], 'learning_rate': [0.1], 'max_depth': [5, 7]}
        }
    }

    for model_name, config in models_config.items():
        if config["params"]:
            grid = GridSearchCV(estimator=config["model"], param_grid=config["params"],
                                cv=3, scoring='neg_mean_squared_error', n_jobs=-1)
            grid.fit(X_train, y_train)
            best_model = grid.best_estimator_
        else:
            best_model = config["model"]
            best_model.fit(X_train, y_train)

        trained_models[model_name] = best_model

        # Évaluation
        y_pred_scaled = best_model.predict(X_test)
        y_pred_prices = scaler_close.inverse_transform(y_pred_scaled.reshape(-1, 1)).flatten()
        all_predictions[model_name] = y_pred_prices

        mse  = mean_squared_error(y_test_raw, y_pred_prices)
        rmse = np.sqrt(mse)
        mae  = mean_absolute_error(y_test_raw, y_pred_prices)

        performance_records.append({"Modèle": model_name, "RMSE": round(rmse, 4), "MAE": round(mae, 4)})

    # Graphique global sur le Test Set sauvegardé automatiquement
    plt.figure(figsize=(12, 6))
    plt.plot(y_test_raw, color='black', label='Valeurs réelles', linewidth=2)

    colors = {"Régression Linéaire": "green", "Random Forest": "orange", "KNN": "purple",
              "XGBoost": "blue", "LightGBM": "brown"}

    for model_name, preds in all_predictions.items():
        plt.plot(preds, color=colors[model_name], label=model_name, linestyle='--', alpha=0.7)

    plt.title(f"Prédictions sur Test Set - {company_name}")
    plt.xlabel("Jours")
    plt.ylabel("Prix ($)")
    plt.legend()
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.savefig(os.path.join(PLOTS_DIR, f"test_predictions_{company_name.replace(' ', '_')}.png"), dpi=150)
    plt.close()

    df_summary = pd.DataFrame(performance_records).set_index("Modèle")
    return df_summary, trained_models


# =====================================================================
#  3. PRÉDICTION ITÉRATIVE MULTI-JOURS (FUTUR)
# =====================================================================

def predict_multistep(model, last_window_close, last_feats, scaler_close, n_future_days):
    predictions_scaled = []
    window_close = last_window_close.copy()

    for _ in range(n_future_days):
        x_input   = np.concatenate([window_close, last_feats]).reshape(1, -1)
        next_pred = model.predict(x_input)[0]
        predictions_scaled.append(next_pred)
        window_close = np.append(window_close[1:], next_pred)

    return scaler_close.inverse_transform(np.array(predictions_scaled).reshape(-1, 1)).flatten()


def plot_multistep_forecast(y_raw, trained_models, last_window, last_feats, scaler_close, n_future, company_name):
    plt.figure(figsize=(12, 5))
    plt.plot(y_raw[:n_future], color='black', linewidth=2.5, label='Valeurs Réelles (Futur)')

    colors  = {"Régression Linéaire": "green", "Random Forest": "orange", "KNN": "purple",
               "XGBoost": "blue", "LightGBM": "brown"}

    records = []
    for model_name, model in trained_models.items():
        preds = predict_multistep(model, last_window, last_feats, scaler_close, n_future)
        rmse  = np.sqrt(mean_squared_error(y_raw[:n_future], preds))
        records.append({"Modèle": model_name, f"RMSE ({n_future}j)": round(rmse, 4)})

        plt.plot(preds, color=colors[model_name], linestyle='--', marker='o', markersize=4, label=model_name)

    plt.title(f"Projection Auto-Régressive {n_future}j — {company_name}")
    plt.xlabel("Jours futurs")
    plt.ylabel("Prix ($)")
    plt.legend()
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.savefig(os.path.join(PLOTS_DIR, f"forecast_30j_{company_name.replace(' ', '_')}.png"), dpi=150)
    plt.close()

    return pd.DataFrame(records).set_index("Modèle")


# =====================================================================
#  POINT D'ENTRÉE PRINCIPAL
# =====================================================================

def run_tp4(companies_to_process=None):
    print("\n" + "="*60 + "\n LANCEMENT DU TP4 - RÉGRESSION & FORECASTING\n" + "="*60)

    csv_files = glob.glob(os.path.join(HISTORICAL_DIR, "*.csv"))
    if not csv_files:
        print(f"❌ Aucun historique CSV trouvé dans '{HISTORICAL_DIR}'.")
        return

    print(f"🔍 {len(csv_files)} fichiers d'entreprises détectés.")

    for file_path in csv_files:
        filename = os.path.basename(file_path).replace(".csv", "")

        # MODIFICATION : Si companies_to_process est fourni, on filtre. Sinon, on prend TOUT.
        if companies_to_process is not None and filename not in companies_to_process:
            continue

        company_name = filename.replace("_history", "").replace("_", " ")
        print(f"\n Processing : {company_name}...")

        try:
            # 1. Préparation des données
            X_train, X_test, y_train, y_test, scaler, y_raw = prepare_regression_data(file_path, n_days=30)

            # 2. Pipeline d'entraînement et d'évaluation
            df_perf, models = run_regression_pipeline(X_train, X_test, y_train, y_test, scaler, y_raw, company_name)
            print(f" ├─ Synthèse des erreurs sur Test Set :")
            print(df_perf.sort_values(by="RMSE").to_string())

            # 3. Projection 10 jours dans le futur
            last_window = X_train[-1][:30]
            last_feats  = X_train[-1][30:]
            df_forecast = plot_multistep_forecast(y_raw, models, last_window, last_feats, scaler, n_future=10, company_name=company_name)

            print(f" ├─ Synthèse Projection Future (10 jours) :")
            print(df_forecast.sort_values(by="RMSE (10j)").to_string())
            print(f"✅ Terminé pour {company_name}. Graphiques sauvegardés dans '{PLOTS_DIR}'.")

        except Exception as e:
            print(f"❌ Erreur sur {company_name} : {e}")


if __name__ == "__main__":
    # En laissant les parenthèses vides, le script va scanner et exécuter TOUTES les entreprises !
    run_tp4()
