# -*- coding: utf-8 -*-
"""TP5_DeepLearning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18EUP2qLBaj7AkZq4XZwEmBtHEs3YB_Nr
"""

# ============================================================
#  TP5 — Deep Learning pour la prédiction de prix
#  Architecture de Production (MLP, RNN, LSTM, Hybride)
# ============================================================

import os
import glob
import itertools
import warnings
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Désactiver les avertissements massifs de TensorFlow
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
import tensorflow as tf

from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.ensemble import RandomForestRegressor

from ta.trend import SMAIndicator, EMAIndicator, MACD
from ta.momentum import RSIIndicator, ROCIndicator
from ta.volatility import BollingerBands

warnings.filterwarnings("ignore")

# ── Chemins et Constantes ──────────────────────────────────
HISTORICAL_DIR = "Companies_historical_data"
PLOTS_DIR      = "plots_tp5"
os.makedirs(PLOTS_DIR, exist_ok=True)


# =====================================================================
#  1. PRÉPARATION DES DONNÉES (2D & 3D)
# =====================================================================

def prepare_dl_dataset(file_path, n_days=30, test_size=0.2):
    """ Prépare les données pour le Machine Learning (2D) et le Deep Learning (3D). """
    df = pd.read_csv(file_path, index_col=0)
    df.index = pd.to_datetime(df.index)
    df = df.sort_index()[['Close']].copy()

    # Features stationnaires
    sma_20      = SMAIndicator(df['Close'], window=20).sma_indicator()
    ema_20      = EMAIndicator(df['Close'], window=20).ema_indicator()
    macd_obj    = MACD(df['Close'])
    macd_raw    = macd_obj.macd()
    macd_signal = macd_obj.macd_signal()
    bb          = BollingerBands(df['Close'])
    bb_high     = bb.bollinger_hband()
    bb_low      = bb.bollinger_lband()
    bb_range    = bb_high - bb_low

    df['RSI_14']                 = RSIIndicator(df['Close'], window=14).rsi()
    df['ROC_10']                 = ROCIndicator(df['Close'], window=10).roc()
    df['Volatility_20']          = df['Close'].pct_change().rolling(20).std()
    df['price_vs_sma']           = df['Close'] / sma_20
    df['price_vs_ema']           = df['Close'] / ema_20
    df['bollinger_pct']          = np.where(bb_range != 0, (df['Close'] - bb_low) / bb_range, 0.5)
    df['macd_normalized']        = macd_raw    / df['Close']
    df['macd_signal_normalized'] = macd_signal / df['Close']
    df['month']                  = df.index.month
    df = df.dropna()

    feature_cols = [c for c in df.columns if c != 'Close']
    n_features   = len(feature_cols)

    split_idx = int(len(df) * (1 - test_size))
    train_df, test_df = df.iloc[:split_idx], df.iloc[split_idx:]

    scaler_close    = MinMaxScaler()
    scaler_features = MinMaxScaler()

    train_close_s    = scaler_close.fit_transform(train_df[['Close']])
    train_features_s = scaler_features.fit_transform(train_df[feature_cols])
    test_close_s     = scaler_close.transform(test_df[['Close']])
    test_features_s  = scaler_features.transform(test_df[feature_cols])

    def make_sequences(close_s, features_s, n):
        X2d, X3d, Y = [], [], []
        for i in range(n, len(close_s)):
            window   = close_s[i-n:i].flatten()      # (30,)
            feats    = features_s[i]                 # (n_features,)
            combined = np.concatenate([window, feats])
            X2d.append(combined)
            X3d.append(combined.reshape(-1, 1))      # (30+n_features, 1) pour RNN/LSTM
            Y.append(close_s[i, 0])
        return np.array(X2d), np.array(X3d), np.array(Y)

    X_tr_2d, X_tr_3d, y_tr = make_sequences(train_close_s, train_features_s, n_days)
    X_te_2d, X_te_3d, y_te = make_sequences(test_close_s,  test_features_s,  n_days)

    y_test_raw = scaler_close.inverse_transform(y_te.reshape(-1, 1)).flatten()
    input_dim  = n_days + n_features

    return X_tr_2d, X_te_2d, X_tr_3d, X_te_3d, y_tr, y_te, scaler_close, y_test_raw, input_dim


# =====================================================================
#  2. ARCHITECTURES DE DEEP LEARNING
# =====================================================================

def build_mlp_model(input_dim, hidden_dims, dropout_rate, activation, optimizer):
    model = tf.keras.Sequential()
    model.add(tf.keras.layers.Dense(hidden_dims[0], activation=activation, input_shape=(input_dim,)))
    model.add(tf.keras.layers.Dropout(dropout_rate))
    for dim in hidden_dims[1:]:
        model.add(tf.keras.layers.Dense(dim, activation=activation))
        model.add(tf.keras.layers.Dropout(dropout_rate))
    model.add(tf.keras.layers.Dense(1))
    model.compile(optimizer=optimizer, loss='mse')
    return model

def build_rnn_model(input_shape, hidden_dims, dropout_rate, activation, optimizer):
    model = tf.keras.Sequential()
    model.add(tf.keras.layers.SimpleRNN(hidden_dims[0], activation=activation,
                                        return_sequences=len(hidden_dims)>1, input_shape=input_shape))
    model.add(tf.keras.layers.Dropout(dropout_rate))
    for i, dim in enumerate(hidden_dims[1:]):
        model.add(tf.keras.layers.SimpleRNN(dim, activation=activation, return_sequences=i < len(hidden_dims)-2))
        model.add(tf.keras.layers.Dropout(dropout_rate))
    model.add(tf.keras.layers.Dense(1))
    model.compile(optimizer=optimizer, loss='mse')
    return model

def build_lstm_model(input_shape, hidden_dims, dropout_rate, activation, optimizer):
    model = tf.keras.Sequential()
    model.add(tf.keras.layers.LSTM(hidden_dims[0], activation=activation,
                                   return_sequences=len(hidden_dims)>1, input_shape=input_shape))
    model.add(tf.keras.layers.Dropout(dropout_rate))
    for i, dim in enumerate(hidden_dims[1:]):
        model.add(tf.keras.layers.LSTM(dim, activation=activation, return_sequences=i < len(hidden_dims)-2))
        model.add(tf.keras.layers.Dropout(dropout_rate))
    model.add(tf.keras.layers.Dense(1))
    model.compile(optimizer=optimizer, loss='mse')
    return model

def build_hybrid_model(input_shape, lstm_units, dense_units, dropout_rate, optimizer):
    model = tf.keras.Sequential()
    model.add(tf.keras.layers.LSTM(lstm_units, activation='tanh', input_shape=input_shape, return_sequences=False))
    model.add(tf.keras.layers.Dropout(dropout_rate))
    for units in dense_units:
        model.add(tf.keras.layers.Dense(units, activation='relu'))
        model.add(tf.keras.layers.Dropout(dropout_rate))
    model.add(tf.keras.layers.Dense(1))
    model.compile(optimizer=optimizer, loss='mse')
    return model


# =====================================================================
#  3. ENTRAÎNEMENT ET OPTIMISATION (GRID SEARCH DL)
# =====================================================================

def run_dl_pipeline(X_tr_2d, X_te_2d, X_tr_3d, X_te_3d, y_tr, y_te, scaler_close, y_raw, input_dim):
    """ Recherche les meilleurs hyperparamètres pour chaque architecture DL. """
    best_models = {}

    # Grille réduite pour un temps d'exécution raisonnable
    dl_configs = [
        {"hidden_dims": [64, 32], "lr": 0.001, "drop": 0.0},
        {"hidden_dims": [128, 64], "lr": 0.001, "drop": 0.2}
    ]

    for model_type in ["MLP", "RNN", "LSTM"]:
        best_rmse = float('inf')
        best_cfg  = None

        X_tr = X_tr_2d if model_type == "MLP" else X_tr_3d
        X_te = X_te_2d if model_type == "MLP" else X_te_3d
        in_shape = input_dim if model_type == "MLP" else (input_dim, 1)

        for cfg in dl_configs:
            opt = tf.keras.optimizers.Adam(learning_rate=cfg["lr"])
            act = "tanh" if model_type in ["RNN", "LSTM"] else "relu"

            if model_type == "MLP":
                m = build_mlp_model(in_shape, cfg["hidden_dims"], cfg["drop"], act, opt)
            elif model_type == "RNN":
                m = build_rnn_model(in_shape, cfg["hidden_dims"], cfg["drop"], act, opt)
            else:
                m = build_lstm_model(in_shape, cfg["hidden_dims"], cfg["drop"], act, opt)

            # Entraînement silencieux
            m.fit(X_tr, y_tr, epochs=15, batch_size=32, verbose=0)

            preds = scaler_close.inverse_transform(m.predict(X_te, verbose=0).reshape(-1, 1)).flatten()
            rmse  = np.sqrt(mean_squared_error(y_raw, preds))

            if rmse < best_rmse:
                best_rmse = rmse
                best_cfg = {
                    "model": m, "name": f"{model_type} {cfg['hidden_dims']}",
                    "preds": preds,
                    "metrics": {"MSE": round(mean_squared_error(y_raw, preds),4),
                                "RMSE": round(rmse,4),
                                "MAE": round(mean_absolute_error(y_raw, preds),4)}
                }
        best_models[model_type] = best_cfg

    # Modèle Hybride
    best_hybrid_rmse = float('inf')
    for lstm_u, dense_u in [(64, [32]), (128, [64, 32])]:
        opt = tf.keras.optimizers.Adam(learning_rate=0.001)
        m = build_hybrid_model((input_dim, 1), lstm_u, dense_u, 0.2, opt)
        m.fit(X_tr_3d, y_tr, epochs=15, batch_size=32, verbose=0)

        preds = scaler_close.inverse_transform(m.predict(X_te_3d, verbose=0).reshape(-1, 1)).flatten()
        rmse  = np.sqrt(mean_squared_error(y_raw, preds))

        if rmse < best_hybrid_rmse:
            best_hybrid_rmse = rmse
            best_models["Hybrid"] = {
                "model": m, "name": f"Hybrid LSTM({lstm_u})+MLP", "preds": preds,
                "metrics": {"MSE": round(mean_squared_error(y_raw, preds),4),
                            "RMSE": round(rmse,4), "MAE": round(mean_absolute_error(y_raw, preds),4)}
            }

    return best_models


# =====================================================================
#  4. PRÉDICTION ITÉRATIVE MULTI-JOURS
# =====================================================================

def predict_multistep_dl(model, model_type, last_sequence, scaler_close, n_future_days):
    predictions_scaled = []
    current_seq = last_sequence.copy()
    seq_len = current_seq.shape[0]

    for _ in range(n_future_days):
        x_input = current_seq.reshape(1, -1) if model_type == "MLP" else current_seq.reshape(1, seq_len, 1)
        next_pred = model.predict(x_input, verbose=0)[0][0]

        # Glissement : Seul le prix (les 30 premiers éléments) se décale, les features restent fixes.
        new_seq = current_seq.copy()
        new_seq[:29] = current_seq[1:30]
        new_seq[29]  = next_pred
        current_seq  = new_seq

        predictions_scaled.append(next_pred)

    return scaler_close.inverse_transform(np.array(predictions_scaled).reshape(-1, 1)).flatten()


# =====================================================================
#  POINT D'ENTRÉE PRINCIPAL
# =====================================================================

def run_tp5(companies_to_process=None):
    print("\n" + "="*60 + "\n LANCEMENT DU TP5 - DEEP LEARNING (RÉSEAUX DE NEURONES)\n" + "="*60)

    csv_files = glob.glob(os.path.join(HISTORICAL_DIR, "*.csv"))
    if not csv_files:
        print(f"❌ Aucun historique CSV trouvé dans '{HISTORICAL_DIR}'.")
        return

    if companies_to_process is None:
        companies_to_process = ["Apple", "Microsoft"] # Réduit par défaut car le DL est long

    for file_path in csv_files:
        filename = os.path.basename(file_path).replace(".csv", "")
        if filename not in companies_to_process:
            continue

        company_name = filename.replace("_history", "").replace("_", " ")
        print(f"\n🧠 Entraînement Deep Learning pour : {company_name}...")

        try:
            # 1. Données
            (X_tr_2d, X_te_2d, X_tr_3d, X_te_3d, y_tr, y_te,
             scaler_close, y_raw, input_dim) = prepare_dl_dataset(file_path)

            # 2. Entraîner Baseline ML (Random Forest) pour comparaison autonome
            rf = RandomForestRegressor(n_estimators=100, random_state=42)
            rf.fit(X_tr_2d, y_tr)
            rf_preds = scaler_close.inverse_transform(rf.predict(X_te_2d).reshape(-1, 1)).flatten()
            rf_metrics = {"MSE": round(mean_squared_error(y_raw, rf_preds),4),
                          "RMSE": round(np.sqrt(mean_squared_error(y_raw, rf_preds)),4),
                          "MAE": round(mean_absolute_error(y_raw, rf_preds),4)}

            # 3. Entraîner et optimiser Modèles DL
            dl_models = run_dl_pipeline(X_tr_2d, X_te_2d, X_tr_3d, X_te_3d, y_tr, y_te, scaler_close, y_raw, input_dim)

            # 4. Synthèse globale ML vs DL
            rows = [{"Modèle": "Baseline ML (Random Forest)", **rf_metrics}]
            for m_type, cfg in dl_models.items():
                rows.append({"Modèle": f"{cfg['name']} (DL)", **cfg["metrics"]})

            df_perf = pd.DataFrame(rows).set_index("Modèle")
            print(f" ├─ Synthèse des erreurs sur Test Set :")
            print(df_perf.sort_values(by="RMSE").to_string())

            # 5. Graphique : Confrontation Finale sur Test Set
            plt.figure(figsize=(14, 6))
            plt.plot(y_raw, color='black', linewidth=2.5, label='Valeurs réelles')
            plt.plot(rf_preds, color='grey', linestyle='-.', label='Baseline ML (Random Forest)')

            colors = {"MLP": "green", "RNN": "orange", "LSTM": "blue", "Hybrid": "purple"}
            for m_type, cfg in dl_models.items():
                plt.plot(cfg["preds"], color=colors[m_type], linestyle='--', label=cfg["name"])

            plt.title(f"Confrontation Finale ML vs DL — {company_name}")
            plt.xlabel("Jours") ; plt.ylabel("Prix ($)")
            plt.legend() ; plt.grid(True, alpha=0.3)
            plt.tight_layout()
            plt.savefig(os.path.join(PLOTS_DIR, f"test_ml_vs_dl_{company_name.replace(' ', '_')}.png"), dpi=150)
            plt.close()

            # 6. Prédiction Itérative (Futur 10j)
            print(" ├─ Génération des projections futures (10 jours)...")
            n_future = 10
            real_future = y_raw[:n_future]

            plt.figure(figsize=(12, 5))
            plt.plot(real_future, color='black', linewidth=2, label='Réalité (Futur)')

            for m_type, cfg in dl_models.items():
                last_seq = X_tr_2d[-1].copy() if m_type == "MLP" else X_tr_3d[-1].copy()
                preds = predict_multistep_dl(cfg["model"], m_type, last_seq, scaler_close, n_future)
                plt.plot(preds, color=colors[m_type], linestyle='--', marker='o', markersize=4, label=cfg["name"])

            plt.title(f"Projection Itérative DL {n_future}j — {company_name}")
            plt.legend() ; plt.grid(True, alpha=0.3)
            plt.tight_layout()
            plt.savefig(os.path.join(PLOTS_DIR, f"forecast_dl_{company_name.replace(' ', '_')}.png"), dpi=150)
            plt.close()

            print(f"✅ Terminé pour {company_name}. Graphiques sauvegardés dans '{PLOTS_DIR}'.")

        except Exception as e:
            print(f"❌ Erreur sur {company_name} : {e}")

if __name__ == "__main__":
    run_tp5()

