# -*- coding: utf-8 -*-
"""TP6_Scrapping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18I8eHTvdm2fXbkg7peZdevmcYTa0bYAt
"""

# ============================================================
#  TP6 — Scrapping des News Financières via NewsAPI
#  Architecture de Production
# ============================================================

import os
import time
import json
import requests
import pandas as pd
from datetime import datetime, timedelta

# ── Constantes et Configuration ────────────────────────────
NEWS_FOLDER = "companies_news"
os.makedirs(NEWS_FOLDER, exist_ok=True)

# Groupes géographiques
ASIAN_SUFFIXES    = [".KS", ".T", "TCEHY", "BABA", "BIDU", "JD", "BYDDY", "1398.HK", "NTDOY", "HYMLF", "RELIANCE.NS", "TCS.NS"]
EUROPEAN_SUFFIXES = [".PA", ".L", ".DE", ".AS"]

SOURCES_US     = "financial-post,the-wall-street-journal,bloomberg,the-washington-post,reuters,the-economist,business-insider,fortune,forbes,cnbc,the-verge,techcrunch,wired,ars-technica,engadget,bbc-news,the-guardian-uk,independent,al-jazeera-english,associated-press"
SOURCES_EUROPE = "bbc-news,the-guardian-uk,independent,reuters,the-economist,financial-post,bloomberg,al-jazeera-english,associated-press,business-insider,fortune,forbes,cnbc,le-monde,handelsblatt,der-spiegel,ansa,rtl-nieuws,les-echos,el-mundo"
SOURCES_ASIA   = "reuters,bloomberg,bbc-news,al-jazeera-english,associated-press,the-economist,cnbc,fortune,business-insider,financial-post,the-japan-times,the-straits-times,south-china-morning-post,nikkei,hindustan-times,the-times-of-india,the-hindu,asia-times,channel-news-asia,the-diplomat"

SEARCH_NAMES = {
    "Louis Vuitton (LVMH)": "LVMH",
    "JP Morgan": "JPMorgan",
    "Johnson & Johnson": "Johnson Johnson",
    "Tata Consultancy Services": "TCS",
    "Reliance Industries": "Reliance",
    "JD.com": "JD.com",
}


# =====================================================================
#  FONCTIONS UTILITAIRES
# =====================================================================

def _get_geographic_sources(ticker):
    """ Retourne la liste des sources adaptée à la géographie du ticker. """
    if any(s in ticker for s in ASIAN_SUFFIXES):
        return SOURCES_ASIA
    elif any(ticker.endswith(s) for s in EUROPEAN_SUFFIXES):
        return SOURCES_EUROPE
    return SOURCES_US


def _get_search_name(company):
    """ Adapte le nom de l'entreprise pour optimiser la recherche de news. """
    return SEARCH_NAMES.get(company, company)


def load_existing_news(company_name):
    """ Charge le fichier JSON existant s'il y en a un pour éviter les doublons. """
    file_path = os.path.join(NEWS_FOLDER, f"{company_name.replace(' ', '_')}.json")
    if os.path.exists(file_path):
        with open(file_path, "r", encoding='utf-8') as f:
            return json.load(f)
    return {}


# =====================================================================
#  CŒUR DU PIPELINE
# =====================================================================

def get_news_by_date(company_name, ticker, api_key, days_back=10):
    """ Scrape les articles pertinents sur NewsAPI et les sauvegarde. """
    url = 'https://newsapi.org/v2/everything'
    last_day  = datetime.today().strftime('%Y-%m-%d')
    first_day = (datetime.today() - timedelta(days=days_back)).strftime('%Y-%m-%d')
    search_query = _get_search_name(company_name)

    params = {
        "sources": _get_geographic_sources(ticker),
        "q": search_query,
        "apiKey": api_key,
        "language": "en",
        "pageSize": 100,
        "from": first_day,
        "to": last_day,
        "sortBy": "relevancy",
    }

    news_dict = load_existing_news(company_name)

    try:
        response = requests.get(url, params=params)
    except Exception as e:
        print(f"❌ Erreur de connexion pour {company_name} : {e}")
        return news_dict

    if response.status_code != 200:
        message = response.json().get('message', 'Erreur inconnue')
        print(f"❌ Erreur API {response.status_code} pour {company_name} : {message}")
        return news_dict

    articles  = response.json().get("articles", [])
    new_count = 0

    for article in articles:
        title       = article.get("title", "") or ""
        description = article.get("description", "") or ""
        source      = article.get("source", {}).get("name", "")
        published   = article.get("publishedAt", "")

        # Filtre strict : le nom de l'entreprise doit être dans le titre ou la description
        if search_query.lower() not in title.lower() and search_query.lower() not in description.lower():
            continue

        if not published:
            continue

        date = published.split("T")[0]
        if date not in news_dict:
            news_dict[date] = []

        existing_titles = [a["title"] for a in news_dict[date]]
        if title not in existing_titles:
            news_dict[date].append({
                "title": title,
                "description": description,
                "source": source,
                "publishedAt": published,
            })
            new_count += 1

    file_path = os.path.join(NEWS_FOLDER, f"{company_name.replace(' ', '_')}.json")
    with open(file_path, "w", encoding='utf-8') as f:
        json.dump(news_dict, f, indent=4, ensure_ascii=False)

    print(f"✅ {company_name} — {new_count} nouveaux articles ajoutés → {file_path}")
    return news_dict


# =====================================================================
#  POINT D'ENTRÉE PRINCIPAL
# =====================================================================

def run_tp6(companies_dict, api_key):
    """
    Fonction principale à appeler depuis le main.py
    companies_dict : Dictionnaire au format {"Nom": "Ticker"} issu du TP1
    """
    print("\n" + "="*50 + "\n LANCEMENT DU TP6 - SCRAPPING NEWS\n" + "="*50)

    if not api_key or api_key == "VOTRE_CLE_API_ICI":
        print("❌ ERREUR: Clé API manquante. Allez sur newsapi.org pour en générer une.")
        return {}

    all_news = {}

    for i, (company, ticker) in enumerate(companies_dict.items()):
        all_news[company] = get_news_by_date(company, ticker, api_key)

        # Pause pour éviter de se faire bloquer par l'API (Rate limiting)
        time.sleep(1)
        if (i + 1) % 20 == 0:
            print("⏸️ Pause de sécurité (30 secondes) pour éviter le blocage API...")
            time.sleep(30)

    print("\n✅ Scrapping terminé. Tous les fichiers JSON sont dans le dossier local 'companies_news/'.")

    # Résumé rapide
    print("\n--- Bilan des articles en mémoire ---")
    for company, news in all_news.items():
        total = sum(len(articles) for articles in news.values())
        print(f" - {company} : {total} articles")

    return all_news


if __name__ == "__main__":
    # 1. Collez ici TOUT votre dictionnaire du TP1
    mes_vraies_entreprises = {
        "Apple": "AAPL",
        "Microsoft": "MSFT",
        "Amazon": "AMZN",
        "Alphabet": "GOOGL",
        "Meta": "META",
        "Tesla": "TSLA",
        "NVIDIA": "NVDA",
        "Samsung": "005930.KS",
        "Tencent": "TCEHY",
        "Baidu": "BIDU",
        "JD.com": "JD",
        "BYD": "BYDDY",
        "ICBC": "1398.HK",
        "Toyota": "TM",
        "SoftBank": "9984.T",
        "Nintendo": "NTDOY",
        "Hyundai": "HYMTF", # ou 005380.KS selon votre correction du TP1
        "Reliance Industries": "RELIANCE.NS",
        "Tata Consultancy Services": "TCS.NS",
        "Alibaba": "BABA",
        "IBM": "IBM",
        "Intel": "INTC",
        "Oracle": "ORCL",
        "Sony": "SONY",
        "Adobe": "ADBE",
        "Netflix": "NFLX",
        "AMD": "AMD",
        "Qualcomm": "QCOM",
        "Cisco": "CSCO",
        "JP Morgan": "JPM",
        "Goldman Sachs": "GS",
        "Visa": "V",
        "Johnson & Johnson": "JNJ",
        "Pfizer": "PFE",
        "ExxonMobil": "XOM",
        "ASML": "ASML.AS",
        "SAP": "SAP.DE",
        "Siemens": "SIE.DE",
        "Louis Vuitton (LVMH)": "MC.PA",
        "TotalEnergies": "TTE.PA",
        "Shell": "SHEL.L"
    }

    # 2. Récupérez votre clé API (depuis Colab ou votre fichier .env)
    # (Exemple si vous êtes sur Google Colab :)
    from google.colab import userdata
    try:
        my_api_key = userdata.get('NEWS_API_KEY')
    except:
        my_api_key = "VOTRE_CLE_API_ICI"

    # 3. Lancez le scrapping sur TOUTES les entreprises !
    run_tp6(mes_vraies_entreprises, my_api_key)
