# -*- coding: utf-8 -*-
"""TP7_Finetuning_BERT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_xeECjrQ7wPcvshdk-x2ZBh_evBRVqcW
"""

# ============================================================
#  TP7 — Finetuning de LLM (BERT & FinBERT) sur News Financières
#  Architecture de Production
# ============================================================

import os
import warnings
import numpy as np
import pandas as pd
import torch

from datasets import load_dataset, concatenate_datasets, DatasetDict
from transformers import AutoTokenizer, AutoModelForSequenceClassification, Trainer, TrainingArguments
from sklearn.metrics import accuracy_score, precision_recall_fscore_support, classification_report

warnings.filterwarnings("ignore")

# ── Constantes et Configuration ────────────────────────────
MODELS_DIR = "finetuned_models"
os.makedirs(MODELS_DIR, exist_ok=True)


# =====================================================================
#  1. PRÉPARATION DU DATASET
# =====================================================================

def load_and_prepare_datasets():
    """ Charge, nettoie et combine deux datasets financiers. """
    print("\n--- Téléchargement et préparation des datasets ---")
    ds1 = load_dataset("zeroshot/twitter-financial-news-sentiment")
    ds2 = load_dataset("nickmuchi/financial-classification")

    # Renommage de "labels" → "label" pour ds2 afin de matcher ds1
    ds2 = ds2.rename_column("labels", "label")

    ds1 = ds1.select_columns(["text", "label"])
    ds2 = ds2.select_columns(["text", "label"])

    # Création d'un split test pour ds2 (20%)
    ds2_split = ds2["train"].train_test_split(test_size=0.2, seed=42)

    combined = DatasetDict({
        "train": concatenate_datasets([ds1["train"], ds2_split["train"]]),
        "test":  concatenate_datasets([ds1["validation"],  ds2_split["test"]]),
    })

    print(f"✅ Dataset combiné :")
    print(f"  - Train : {len(combined['train'])} exemples")
    print(f"  - Test  : {len(combined['test'])} exemples")

    return combined


# =====================================================================
#  2. ENTRAÎNEMENT ET ÉVALUATION
# =====================================================================

def compute_metrics(eval_pred):
    """ Calcule les métriques d'évaluation pour le Trainer HuggingFace. """
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    precision, recall, f1, _ = precision_recall_fscore_support(labels, predictions, average="weighted", zero_division=0)
    acc = accuracy_score(labels, predictions)
    return {"accuracy": acc, "f1": f1, "precision": precision, "recall": recall}


def train_model(model_name, dataset, batch_size=16, num_epochs=3):
    """ Fonction générique pour finetuner n'importe quel modèle de type BERT. """
    print(f"\n{'='*60}")
    print(f" Finetuning : {model_name}")
    print(f"{'='*60}")

    # 1. Chargement tokenizer et modèle pré-entraînés
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = AutoModelForSequenceClassification.from_pretrained(
        model_name,
        num_labels=3,  # Négatif (0), Neutre (1), Positif (2)
        ignore_mismatched_sizes=True
    )

    # 2. Tokenisation du dataset
    def tokenize(batch):
        return tokenizer(batch["text"], truncation=True, padding="max_length", max_length=128)

    tokenized_train = dataset["train"].map(tokenize, batched=True)
    tokenized_test  = dataset["test"].map(tokenize, batched=True)

    tokenized_train.set_format("torch", columns=["input_ids", "attention_mask", "label"])
    tokenized_test.set_format("torch",  columns=["input_ids", "attention_mask", "label"])

    # 3. Arguments d'entraînement
    # On sauvegarde les checkpoints intermédiaires dans un dossier temporaire
    output_temp_dir = f"./temp_{model_name.replace('/', '_')}_results"

    training_args = TrainingArguments(
        output_dir=output_temp_dir,
        eval_strategy="epoch",
        save_strategy="epoch",
        logging_strategy="epoch",
        per_device_train_batch_size=batch_size,
        per_device_eval_batch_size=batch_size,
        num_train_epochs=num_epochs,
        weight_decay=0.01,
        report_to="none",
        disable_tqdm=False,
        logging_first_step=True,
        load_best_model_at_end=True,
    )

    # 4. Création du Trainer
    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=tokenized_train,
        eval_dataset=tokenized_test,
        compute_metrics=compute_metrics,
    )

    # 5. Entraînement et évaluation
    print(f"Lancement de l'entraînement pour {num_epochs} époques...")
    trainer.train()
    results = trainer.evaluate()

    print(f"\n--- Résultats globaux {model_name} ---")
    for key, value in results.items():
        print(f"  {key}: {value:.4f}")

    # Affichage du rapport de classification complet
    predictions = trainer.predict(tokenized_test)
    y_pred = np.argmax(predictions.predictions, axis=-1)
    y_true = predictions.label_ids
    print("\nClassification Report :")
    print(classification_report(y_true, y_pred, target_names=["Negative", "Neutral", "Positive"], zero_division=0))

    # 6. Sauvegarde propre des poids définitifs pour le TP8
    save_path = os.path.join(MODELS_DIR, f"{model_name.replace('/', '_')}_finetuned")
    trainer.save_model(save_path)
    tokenizer.save_pretrained(save_path)
    print(f"✅ Modèle et Tokenizer sauvegardés pour la production dans : {save_path}")

    return trainer, results


# =====================================================================
#  POINT D'ENTRÉE PRINCIPAL
# =====================================================================

def run_tp7():
    """ Pilote l'exécution complète du TP7. """
    print("\n" + "="*60 + "\n LANCEMENT DU TP7 - FINETUNING LLM\n" + "="*60)

    device = "GPU/MPS" if torch.cuda.is_available() or torch.backends.mps.is_available() else "CPU"
    print(f"🖥️  Matériel détecté pour l'entraînement : {device}")
    if device == "CPU":
        print("⚠️  ATTENTION : L'entraînement sur CPU peut prendre plusieurs heures.")

    # 1. Chargement des données
    dataset = load_and_prepare_datasets()

    # 2. Entraînement des modèles
    # Vous pouvez réduire num_epochs à 1 pour faire un test rapide de bout en bout
    _, results_bert = train_model(
        model_name="bert-base-uncased",
        dataset=dataset,
        batch_size=16,
        num_epochs=3
    )

    _, results_finbert = train_model(
        model_name="ProsusAI/finbert",
        dataset=dataset,
        batch_size=16,
        num_epochs=3
    )

    # 3. Tableau comparatif
    print("\n" + "="*50 + "\n TABLEAU COMPARATIF FINAL\n" + "="*50)
    df_comparison = pd.DataFrame({
        "Modèle":    ["BERT Base", "FinBERT"],
        "Accuracy":  [results_bert["eval_accuracy"],  results_finbert["eval_accuracy"]],
        "F1-Score":  [results_bert["eval_f1"],        results_finbert["eval_f1"]],
        "Precision": [results_bert["eval_precision"], results_finbert["eval_precision"]],
        "Recall":    [results_bert["eval_recall"],    results_finbert["eval_recall"]],
    })

    # Affichage formaté pour la console (remplace le .style de Jupyter)
    print(df_comparison.round(4).to_string(index=False))

    # Sauvegarde CSV des résultats
    csv_path = os.path.join(MODELS_DIR, "llm_comparison_results.csv")
    df_comparison.to_csv(csv_path, index=False)
    print(f"\n✅ Pipeline TP7 terminé. Résultats sauvegardés dans {csv_path}")

    return df_comparison


if __name__ == "__main__":
    # Assurez-vous d'avoir exécuté : pip install transformers datasets torch scikit-learn pandas
    run_tp7()
