# -*- coding: utf-8 -*-
"""TP8_Classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13Y_SKglgyRNiDXX5FLpUE-5nlSovBNnI
"""

# ============================================================
#  TP8 — Analyse de Sentiment et Impact sur les Prix
#  Architecture de Production
# ============================================================

import os
import json
import warnings
from datetime import datetime, timedelta
from collections import defaultdict

import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
import pytz
import yfinance as yf
import torch
from transformers import BertTokenizer, BertForSequenceClassification

warnings.filterwarnings("ignore")

# ── Chemins et Constantes ──────────────────────────────────
NEWS_FOLDER = "companies_news"
MODELS_DIR  = "finetuned_models"
PLOTS_DIR   = "plots_tp8"
os.makedirs(PLOTS_DIR, exist_ok=True)

# Configuration matérielle pour PyTorch
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "mps" if torch.backends.mps.is_available() else "cpu")

COLOR_MAP = {0: "red", 1: "gold", 2: "green"}
LABEL_MAP = {0: "Negative", 1: "Neutral", 2: "Positive"}


# =====================================================================
#  1. TRAITEMENT DES DONNÉES ET DATES
# =====================================================================

def _get_texts_timestamps(news_data):
    """ Transforme le JSON d'une entreprise en listes de textes et timestamps. """
    ny_tz = pytz.timezone("America/New_York")
    news_texts = []
    news_timestamps = []

    for date, articles in news_data.items():
        for article in articles:
            title       = article.get("title", "") or ""
            description = article.get("description", "") or ""
            text        = f"{title}. {description}".strip()

            published = article.get("publishedAt", "")
            if not published:
                continue

            dt_utc = datetime.strptime(published, "%Y-%m-%dT%H:%M:%SZ")
            dt_utc = pytz.utc.localize(dt_utc)
            dt_ny  = dt_utc.astimezone(ny_tz)

            # Arrondi à l'heure pleine précédente
            dt_ny = dt_ny.replace(minute=0, second=0, microsecond=0)

            news_texts.append(text)
            news_timestamps.append(dt_ny)

    return news_texts, news_timestamps


def _align_timestamps(timestamps):
    """ Aligne les timestamps des news sur les horaires de marché. """
    aligned = []
    for ts in timestamps:
        hour = ts.hour + ts.minute / 60

        if 9.5 <= hour < 15:
            # Pendant les heures de marché → heure de publication
            aligned.append(ts)
        elif 15 <= hour < 24:
            # Après 15h → mappé à 15h le même jour
            aligned.append(ts.replace(hour=15, minute=0, second=0, microsecond=0))
        else:
            # Entre minuit et 9h30 → mappé à 15h la veille
            veille = ts - timedelta(days=1)
            aligned.append(veille.replace(hour=15, minute=0, second=0, microsecond=0))

    return aligned


# =====================================================================
#  2. INFÉRENCE DU MODÈLE (NLP)
# =====================================================================

def get_sentiments(model_path, texts, base_model_name="ProsusAI/finbert"):
    """
    Applique le modèle finetuné pour prédire les sentiments.
    Optimisé pour tourner sur GPU/MPS si disponible.
    """
    tokenizer = BertTokenizer.from_pretrained(base_model_name)
    model     = BertForSequenceClassification.from_pretrained(model_path)

    model.to(DEVICE)
    model.eval()

    sentiments = []
    for text in texts:
        inputs = tokenizer(
            text,
            return_tensors="pt",
            truncation=True,
            padding="max_length",
            max_length=128
        )

        # Déplacement des tenseurs sur la carte graphique
        inputs = {k: v.to(DEVICE) for k, v in inputs.items()}

        with torch.no_grad():
            logits = model(**inputs).logits

        pred = torch.argmax(logits, dim=-1).item()
        sentiments.append(pred)

    return sentiments


# =====================================================================
#  3. VISUALISATION
# =====================================================================

def plot_comparison(df, sentiments_a, sentiments_b, timestamps, title_a, title_b, filename):
    """ Génère et sauvegarde la comparaison graphique. """
    aligned_ts = _align_timestamps(timestamps)

    df = df.copy()
    df["Datetime"] = pd.to_datetime(df["Datetime"])
    if df["Datetime"].dt.tz is None:
        ny_tz = pytz.timezone("America/New_York")
        df["Datetime"] = df["Datetime"].dt.tz_localize("UTC").dt.tz_convert(ny_tz)

    fig, axes = plt.subplots(1, 2, figsize=(18, 6), sharey=False)

    for ax, sentiments, title in zip(axes, [sentiments_a, sentiments_b], [title_a, title_b]):
        ax.plot(df["Datetime"], df["Close"], color="steelblue", linewidth=1.5, label="Prix")

        # Groupement par timestamp
        grouped = defaultdict(list)
        for ts, sent in zip(aligned_ts, sentiments):
            grouped[ts].append(sent)

        # Superposition des points de sentiment
        for ts, sents in grouped.items():
            mask = df["Datetime"] == ts
            price_rows = df[mask]["Close"]

            if price_rows.empty:
                idx = (df["Datetime"] - ts).abs().idxmin()
                price = df.loc[idx, "Close"]
            else:
                price = price_rows.values[0]

            # Décalage vertical pour distinguer plusieurs news au même moment
            for i, sent in enumerate(sents):
                offset = i * (df["Close"].max() - df["Close"].min()) * 0.01
                ax.scatter(ts, price + offset, color=COLOR_MAP[sent], s=60, zorder=5)

        # Légende et formatage
        legend_elements = [
            Line2D([0], [0], color="steelblue", linewidth=1.5, label="Prix"),
            Line2D([0], [0], marker="o", color="w", markerfacecolor="green", markersize=8, label="Positive"),
            Line2D([0], [0], marker="o", color="w", markerfacecolor="gold",  markersize=8, label="Neutral"),
            Line2D([0], [0], marker="o", color="w", markerfacecolor="red",   markersize=8, label="Negative"),
        ]
        ax.legend(handles=legend_elements)
        ax.set_title(title)
        ax.set_xlabel("Date")
        ax.set_ylabel("Prix ($)")
        ax.tick_params(axis="x", rotation=45)

    plt.tight_layout()
    save_path = os.path.join(PLOTS_DIR, f"{filename}.png")
    plt.savefig(save_path, dpi=150)
    plt.close()
    print(f" └─ Graphique sauvegardé : {save_path}")


# =====================================================================
#  POINT D'ENTRÉE PRINCIPAL
# =====================================================================

def run_tp8(companies_to_analyze=None, start_date="2024-05-01"):
    """
    Exécute le pipeline complet du TP8.
    Par défaut, traite un sous-ensemble d'entreprises pour l'analyse.
    """
    print("\n" + "="*60 + "\n LANCEMENT DU TP8 - ANALYSE DE SENTIMENT SUR PRIX\n" + "="*60)
    print(f"🖥️  Inférence exécutée sur : {DEVICE}")

    if companies_to_analyze is None:
        companies_to_analyze = {
            "Microsoft": "MSFT",
            "Meta":      "META",
            "Amazon":    "AMZN",
            "NVIDIA":    "NVDA",
            "Goldman Sachs": "GS",
        }

    # Configuration des chemins modèles (Doivent correspondre aux sorties du TP7)
    finbert_base = "ProsusAI/finbert"
    finbert_finetuned = os.path.join(MODELS_DIR, "ProsusAI_finbert_finetuned")

    if not os.path.exists(finbert_finetuned):
        print(f"⚠️  ATTENTION : Le modèle {finbert_finetuned} est introuvable.")
        print("Veuillez exécuter le TP7 d'abord pour générer le modèle, ou ajustez le chemin.")
        return

    for company, ticker_symbol in companies_to_analyze.items():
        print(f"\n--- Analyse : {company} ---")

        # 1. Chargement des news
        json_path = os.path.join(NEWS_FOLDER, f"{company.replace(' ', '_')}.json")
        if not os.path.exists(json_path):
            print(f" ⚠️ Pas de JSON pour {company}, on passe à la suivante.")
            continue

        with open(json_path, "r", encoding="utf-8") as f:
            news_data = json.load(f)

        # 2. Extraction
        texts, timestamps = _get_texts_timestamps(news_data)
        if not texts:
            print(f" ⚠️ Aucun texte exploitable pour {company}.")
            continue
        print(f" ├─ {len(texts)} articles chargés.")

        # 3. Historique Yahoo Finance (Intervalles de 60 minutes)
        print(f" ├─ Récupération des prix pour {ticker_symbol}...")
        ticker = yf.Ticker(ticker_symbol)
        df = ticker.history(start=start_date, interval="60m")
        if df.empty:
            print(f" ⚠️ Aucune donnée de prix trouvée pour {company}.")
            continue

        df = df.reset_index()
        print(f" ├─ {len(df)} points de prix récupérés.")

        # 4. Inférence (Prédictions NLP)
        print(" ├─ Prédiction FinBERT (Base)...")
        sentiments_base = get_sentiments(finbert_base, texts)

        print(" ├─ Prédiction FinBERT (Finetuné)...")
        sentiments_finetuned = get_sentiments(finbert_finetuned, texts, base_model_name=finbert_base)

        # 5. Graphique
        plot_comparison(
            df=df,
            sentiments_a=sentiments_base,
            sentiments_b=sentiments_finetuned,
            timestamps=timestamps,
            title_a=f"{company} — FinBERT Base",
            title_b=f"{company} — FinBERT Finetuné",
            filename=f"sentiment_vs_price_{company.replace(' ', '_')}"
        )

    print("\n✅ Pipeline TP8 terminé avec succès.")


if __name__ == "__main__":
    run_tp8()
